# docker swarm stack 
version: '3'

services:
  #load balancer and static html server docker application
  lb-static-html:
    image: phylocube-nginx-app
    ports:
      - 80:80

  backend-1:
    image: phylocube-backend-app
    environment:
      - NODE_NAME=phylocube-backend-app-1
    ports:
      - 3000:3000

  backend-2:
    image: phylocube-backend-app 
    environment:
      - NODE_NAME=phylocube-backend-app-2
    ports:
      - 3001:3000